title
alvls/mp1-2020-1 pull request #10
Opened 2020-02-21 21:51 UTC by GolovRibolov

2020-03-01 20:26 UTC, alvls commented
По заданию 1.
1. Не хватает метода 2) узнать время. Вывод на консоль - это другой метод.
2. Названия методов лучше давать на английском, а не латиницей.

В текущем виде так:

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,8
Качество   проектирования: | 1,5
Качество кода: | 1,2
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,5

2020-03-02 19:56 UTC, GolovRibolov commented
Сегодня не было возможности исправить,можно завтра поправить?

2020-03-02 21:11 UTC, alvls commented
Поправить можно. Баллы от этого не увеличатся.

2020-03-02 21:40 UTC, alvls requested changes

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +	int x;
Неудачное имя поля. Это не x, это размер.

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +		}
Циклы написаны неверно. Будет выход за границы массива. Плюс не используется часть памяти. Лучше считайте с нуля.

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +	int outputSize()
Уберите вывод на консоль, поменяйте имя метода.

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +	int outputElement(int i, int j)
Уберите вывод на консоль, поменяйте имя метода.

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +				sum = abs(matrix[i][j]);
Неверно. Здесь должна считаться сумма.

2020-03-02 21:40 UTC, alvls commented on golovkin_n/task2/Source.cpp
> +		for ( i = 1; i < other.x + 1; i++)
Забыли присвоить размер.

2020-03-03 21:02 UTC, alvls commented
Исправьте замечания по заданию 2

2020-03-08 18:43 UTC, alvls commented
Диагональное преобладание все еще считается неверно.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,7
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 2,5
__Итого:__ | 3,2

2020-03-08 20:14 UTC, merged