Task 1
alvls/mp1-2020-1 pull request #11
Opened 2020-02-22 18:03 UTC by Jul-Jak

2020-03-01 20:32 UTC, alvls commented
По заданию 1. В целом неплохо, не считая неудачного названию класса. 

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,3
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,8

2020-03-03 08:12 UTC, alvls requested changes

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	DynamicArr nechet(); //подмассив с нечётными индексами
Поменяйте название на более "говорящее".

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	int test2(); //проверка на упорядоченность по возрастанию
Поменяйте названия на более "говорящие".

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	arr = NULL;
Используйте nullptr вместо NULL

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	if (arr != NULL) free(arr);
Ошибка. Нельзя использовать free в пару к new. Замените на delete. И проверка на NULL не потребуется (delete сам это делает).

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +		free(arr);
Замените на delete

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +		arr[i] = 0;
Почему нули? Копировать кто будет?

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	}
Неверно. Исправьте поиск минимума.

2020-03-03 08:12 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +int DynamicArr::test1()
Лучше вернуть bool

2020-03-03 20:10 UTC, alvls requested changes

2020-03-03 20:10 UTC, alvls commented on jakovleva_ju/task2/Source.cpp
> +	delete(arr);
Неверно. Должно быть так:
```suggestion
	delete [] arr;
```

2020-03-03 20:10 UTC, alvls commented
Исправили не всё

2020-03-04 13:35 UTC, Jul-Jak commented
Здравствуйте! Можно уточнить что именно не так с исправлениями? В поиске минимума я исправила реализацию для общего случая. Что именно надо копировать в 64-67 строках кода? Название и удаление памяти исправлю. Заранее спасибо.

2020-03-04 13:40 UTC, alvls commented
С минимумом все нормально. А в операторе= вы не скопировали данные. Вместо этого вы просто забили массив нулями.

2020-03-04 14:32 UTC, alvls commented
В одном методе осталось free вместо delete.

2020-03-04 14:42 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,5
__Итого:__ | 5,5

2020-03-04 18:51 UTC, merged