Task 1
alvls/mp1-2020-1 pull request #12
Opened 2020-02-22 18:14 UTC by Troeg13

2020-02-28 15:10 UTC, Troeg13 commented
Task1 and task2

2020-03-01 20:49 UTC, alvls commented
По заданию 1. Отлично!

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,5
Штраф: | 0,0
__Итого:__ | 6,5

2020-03-03 08:40 UTC, alvls requested changes

2020-03-03 08:40 UTC, alvls commented on troegubova_aa/task2/VectorClass.cpp
> +	memo = NULL;
Лучше использовать nullptr

2020-03-03 08:40 UTC, alvls commented on troegubova_aa/task2/VectorClass.cpp
> +	if (memo != NULL)
Проверка не нежна. delete это делает сам.

2020-03-03 08:40 UTC, alvls commented on troegubova_aa/task2/VectorClass.cpp
> +	return memo[index];
Здесь и в getComp (setComp) не согласовано. Здесь index, там index - 1. Исправьте в getComp и SetComp.

2020-03-03 10:55 UTC, alvls commented
Теперь отлично!

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,5
Штраф: | 0,0
__Итого:__ | 6,5

2020-03-03 13:57 UTC, merged