task1
alvls/mp1-2020-1 pull request #13
Opened 2020-02-24 12:52 UTC by biareactor

2020-02-29 15:24 UTC, biareactor commented
task 2, polynom

2020-03-02 08:28 UTC, alvls commented
Илья, комментарии по заданию 1. В целом - очень хорошо. Пара замечаний на будущее (в этой версии можете оставить, как есть):
1. Если в конструкторе вы хотите использовать исключения, то не нужно ни использовать в нем блок try, ни ловить исключение там же. Его нужно просто выбросить.
2. В методах класса (у вас в операторе =) не нужно использовать методы доступа к полям. Поля доступны просто по имени. Это и короче и быстрее.  

Оценка за работу.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,3
Штраф: | 1,0
__Итого:__ | 5,3

Учитывая, что вы первый раз мне сдаете, в этот раз штраф (за задержку) я вам спишу. Итого 6.3 балла.

2020-03-03 09:05 UTC, alvls requested changes

2020-03-03 09:05 UTC, alvls commented on bykov_ia/task2/Source.cpp
> +			}
Так неверно. -1 не является выделенным значением. Раз решили проверять номер, то нужно просто бросить исключение. Например, так:
```suggestion
	if (num < 0 || num > power)
		throw "IncorrectNumberCoefficient";
	return coefficients[num];
```

2020-03-03 09:06 UTC, alvls commented
Илья, исправьте конструктор в полиноме, плюс исправьте замечание выше.

2020-03-08 20:22 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 2,5
__Итого:__ | 3,7

2020-03-09 06:53 UTC, merged