1
alvls/mp1-2020-1 pull request #14
Opened 2020-02-25 18:26 UTC by cjl31

2020-03-02 08:41 UTC, alvls commented
Денис, реализация класса неверна. Он должен обрабатывать числа длиной в 64 бита, то есть в границах -2^63 .. +2^63-1. В вашем случае это не так.
Попробуйте выполнить такой код:
```
	Longint a1(10000000000);
	cout <<"a1 = "  << a1;
	Longint b1(10000000000);
```
Увидите, что происходит.

В текущем виде могу оценить так:

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 0,5
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 1,5
__Итого:__ | 2,0

Будете пытаться исправить?

2020-03-02 09:46 UTC, cjl31 commented
Да

2020-03-02 23:51 UTC, cjl31 commented
task 2

2020-03-03 10:48 UTC, alvls requested changes

2020-03-03 10:48 UTC, alvls commented on Bychkov_DA/task2/Source.cpp
> +	void inkomp(const int num, int a1) //������ ���������� �� ������
Неудачное название. Исправьте, например, на getCoord

2020-03-03 10:48 UTC, alvls commented on Bychkov_DA/task2/Source.cpp
> +	void outkomp(int num) //������ ���������� �� ������
1. Метод должен вернуть, а не вывести на экран.
2. Смените название.

2020-03-03 10:48 UTC, alvls commented
Замечания по заданию 2:
1. В методах класса не должно быть вывода на консоль (кроме единственного метода специально для этого предназначенного). Методы должны возвращать свои результаты.
2. Почему класс называется Vectors (множественное число)?
3. Остальные замечания см выше по коду.

2020-03-10 10:43 UTC, alvls commented
По заданию 1 оценку фиксирую.

2020-03-10 10:48 UTC, alvls commented
По заданию 2 оцениваю текущее состояние.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,5
Качество   проектирования: | 1,0
Качество кода: | 1,0
Бонус: | 0,0
Штраф: | 1,5
__Итого:__ | 3,0

2020-03-10 10:48 UTC, merged