2.0 Task
alvls/mp1-2020-1 pull request #21
Opened 2020-03-08 15:39 UTC by Boris991

2020-03-08 15:57 UTC, Boris991 commented
2.0 Task

2020-03-08 16:27 UTC, Boris991 commented
It is 2.0 Task dinamic array

2020-03-08 18:20 UTC, alvls requested changes

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +	DArray& operator=(DArray tmp)
Лучше передавать параметр как `const DArray &tmp`

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +				delete arr;
Неверное удаление

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +			if (SIZE != 0)
Лишнее условие

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +		}
Правильный вариант реализации этого оператора - использовать исключения. Пока предлагаю убрать проверки и оставить только
```
return arr[index];
```

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +	int GetSIZE()  //2) ������ ������ �������,
Почему SIZE заглавными? Сделайте, как везде

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +	int SIZE;
Имя заглавными традиционно используют только для макроопределений. Назовите size.

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +	int ControleGreite()  //6) ���������, �������� �� ������ �������������,
Лучше вернуть bool

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +		if ((Res == 0) || (Res == SIZE - 1))
Условие на упорядоченность неверно.

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +	void Chose(DArray& tmp)  //7) �������� �� ������� ��������� � ���������� � ��������� ���������.
Верните массив через возвращаемый тип

2020-03-08 18:20 UTC, alvls commented on guzanov_b/task2/DArray.h
> +			Res[i] = arr[i * 2];
Вы берете элементы с четными индексами, а нужно с нечетными

2020-03-08 18:20 UTC, alvls commented
Борис, исправьте ошибки

2020-03-10 10:58 UTC, alvls commented
Оценка по текущему состоянию.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 1,5
Качество   проектирования: | 1,0
Качество кода: | 1,0
Бонус: | 0,0
Штраф: | 1,5
__Итого:__ | 2,0

2020-03-10 10:58 UTC, merged