Task 3
alvls/mp1-2020-1 pull request #28
Opened 2020-03-14 12:09 UTC by Boris991

2020-03-16 10:31 UTC, alvls commented
Борис, в текущем виде не годится. Общие замечания:
1. Поля нужно называть так, чтобы из имен было хотя бы примерно понятно, для чего это поле. Однобуквенные имена этому принципу удовлетворяют крайне редко.
2. Число точек табулирования - целое, а не вещественное.
3. Отрезок табулирования это две границы, а не длина, как у вас.
4. Табулирование - это не накопление суммы, а получение таблицы из набора пар: x, f(x).
5. Не хватает метода 1) задать текущую функцию. Конструктора для этого не достаточно.
Исправляйте.

2020-03-17 14:03 UTC, alvls requested changes

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +	float tab(float  left_,float right_, int point_)
1. Зачем здесь параметры? Для их задания в классе есть соответствующие методы.
2. Название неудачное. Лучше использовать глагол, например, tabulate.

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +				rec(val);
Нужно не в файл писать, а сохранять в классе. Для чего завести в нем, например, массив или другое хранилище.

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +			reex();
Вывод на экран должен делаться в отдельном методе, а не здесь.

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +	void rec(float valz)//8) ��������� ���������� ������������� � ����
Название неудачное. Переделать. Например, save_to_file

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +		catch (char* err)
Не нужно ловить здесь исключение, только выбросить. Уберите блок catch. В остальных методах аналогично.

2020-03-17 14:03 UTC, alvls commented on guzanov_b/task3/Tab.h
> +	void reex()
Неудачное название. Поменяйте.

2020-03-17 18:52 UTC, Boris991 commented
1197994@LAPTOP-N3R476DK MINGW64 ~/Desktop/Репозиторий/mp1-2020-1 (master)
$ git push
To https://github.com/Boris991/mp1-2020-1
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Boris991/mp1-2020-1'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1197994@LAPTOP-N3R476DK MINGW64 ~/Desktop/Репозиторий/mp1-2020-1 (master)
$ ^C

1197994@LAPTOP-N3R476DK MINGW64 ~/Desktop/Репозиторий/mp1-2020-1 (master)
$ ^C

1197994@LAPTOP-N3R476DK MINGW64 ~/Desktop/Репозиторий/mp1-2020-1 (master)
$

2020-03-17 18:54 UTC, Boris991 commented
Александр Владимирович, добрый вечер, подскажите, пожалуйста, в чем ошибка в git push

2020-03-17 19:25 UTC, alvls commented
Все написано в описании ошибки (по-английски, конечно).
Вам нужно сначала забрать с github ваш репозиторий (git pull), поскольку я вносил в него изменения, чтобы разрешить конфликты слияния.	 И уже после этого вносить ваши изменения.

2020-03-17 19:36 UTC, Boris991 commented
Получилось,спасибо.Я отправил исправленный вариант.С уважением,Гузанов Борис 17.03.2020, 22:25, "Alexander Sysoyev" <notifications@github.com>: Все написано в описании ошибки (по-английски, конечно).Вам нужно сначала забрать с github ваш репозиторий (git pull), поскольку я вносил в него изменения, чтобы разрешить конфликты слияния. И уже после этого вносить ваши изменения.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-17 19:42 UTC, Boris991 commented
Александр Владимирович,подскажите,пожалуйста,как вы оцениваете задачи.С уважением,Гузанов Борис17.03.2020, 22:25, "Alexander Sysoyev" <notifications@github.com>:
Все написано в описании ошибки (по-английски, конечно).
Вам нужно сначала забрать с github ваш репозиторий (git pull), поскольку я вносил в него изменения, чтобы разрешить конфликты слияния.	 И уже после этого вносить ваши изменения.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-17 19:46 UTC, alvls requested changes

2020-03-17 19:46 UTC, alvls commented on guzanov_b/task3/Tab.h
> +		std::cout << "Destructor works!" << endl;
Уберить печать.

2020-03-17 19:46 UTC, alvls commented on guzanov_b/task3/Tab.h
> +		size = _n;
Размер массива для хранения результатов должен совпадать с числом точек для табулирования. Поэтому из point и size нужно оставить один параметр.

2020-03-17 19:46 UTC, alvls commented on guzanov_b/task3/Tab.h
> +				save_to_file(val,flag);
В этом методе должно быть только табулирование. Сохранение должно быть отдельно.

2020-03-17 19:46 UTC, alvls commented on guzanov_b/task3/Tab.h
> +			cout << arr[j] << endl;
Вывод на экран должен быть отдельным методом

2020-03-17 19:46 UTC, alvls commented on guzanov_b/task3/Tab.h
> +		arr = new float[size];
Ошибка. Выделение памяти нужно только при удалении.

2020-03-17 19:48 UTC, alvls commented
Я оцениваю:
1. Функциональность - что из требований в постановке задачи выполнено и как.
2. Качество   проектирования - насколько логично и удобно построен интерфейс класса/классов.
3. Качество кода - насколько хорошо оформлен код, включая отступы, имена переменных и т.д.
4. Бонус - если есть за что.
5. Штраф - при опоздании со сдачей или если долго не исправляются мои замечания.

2020-03-17 21:05 UTC, alvls commented
Успех все ближе )).
1. Удалите cout из tabulate.
2. Сделайте, чтобы read_file читал в хранилище, а не на экран.
3. Добавьте метод вывода на экран.

2020-03-18 13:24 UTC, Boris991 commented
Александр Владимирович, добрый день, я исправил ошибкиС уважением,Гузанов Борис18.03.2020, 00:05, "Alexander Sysoyev" <notifications@github.com>: Успех все ближе )).Удалите cout из tabulate.Сделайте, чтобы read_file читал в хранилище, а не на экран.Добавьте метод вывода на экран.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-18 18:05 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,5
__Итого:__ | 7,0

2020-03-19 20:58 UTC, closed without merging

2020-03-25 15:10 UTC, Boris991 commented
Добрый вечер,Александр Владимирович.Я решил task 4,проверьте,пожалуйста.С уважением,Гузанов Борис

2020-03-25 18:56 UTC, alvls commented
Борис, создайте новый пулл-реквест.

2020-03-26 08:36 UTC, Boris991 commented
Добрый день,Александр Владимирович.Я создал новый pullrequest.С уважением,Гузанов Борис 25.03.2020, 21:57, "Alexander Sysoyev" <notifications@github.com>:
Борис, создайте новый пулл-реквест.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-27 14:44 UTC, Boris991 commented
Здравствуйте,Александр Владимирович.Вы проверили task 4.Я создал новый pullrequest.C уважением,Гузанов Борис25.03.2020, 21:57, "Alexander Sysoyev" <notifications@github.com>:
Борис, создайте новый пулл-реквест.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-27 14:47 UTC, alvls commented
Борис, когда проверю, напишу здесь. Если комментариев не появилось, значит, еще не проверил.