Do you need a few kilograms of potatoes?
alvls/mp1-2020-1 pull request #3
Opened 2020-02-20 12:47 UTC by AnasteishA-1610

2020-03-01 17:27 UTC, alvls commented
По заданию 1. В целом все неплохо.
Замечания:
1. Не хватает метода, позволяющего узнать вес в килограммах. 
2. Названия методов лучше делать более точными, например, convert_to_carat.

2020-03-02 11:10 UTC, alvls commented
По заданию 2. Все хорошо. Есть только одно замечание: метод 5) выделить подстроку из строки нужно исправить. Результатом должна быть строка, а у вас - символ.

2020-03-03 13:49 UTC, AnasteishA-1610 commented
В таск1 поправила названия методов, а разве метод show_kg не "позволяет узнать вес в килограммах"? Нужно что-то другое, я не совсем понимаю

2020-03-03 13:53 UTC, alvls commented
Метод show_kg позволяет вывести на экран. А метод "узнать" должен давать возможность использовать вес в программе, т.е. должен его вернуть.

2020-03-03 17:17 UTC, alvls commented
По заданию 1.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2020-03-03 17:19 UTC, alvls requested changes

2020-03-03 17:19 UTC, alvls commented on plenkova_ad/task2/Source.cpp
> +	char GetPartOfString(int k)
Неверно. Нужно вернуть подстроку, а не символ.

2020-03-03 20:24 UTC, alvls commented
По заданию 2.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2020-03-03 20:24 UTC, merged