Task4
alvls/mp1-2020-1 pull request #42
Opened 2020-03-26 22:46 UTC by samburovam

2020-03-31 14:07 UTC, alvls requested changes

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +		weekdays.resize(0);
Это лишнее. Класс вектор сам все почистит.

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +	int** GetInfo(int step)
В чем назначение этого метода?

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +	int GetCounter(int step)
В чем назначение этого метода?

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +		return sum / records;
Если records будет равен нулю, программа упадет. Исправьте.

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +		return sum / k;
Если k будет равен нулю, программа упадет. Исправьте.

2020-03-31 14:07 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +		return sum / k;
Если k будет равен нулю, программа упадет. Исправьте.

2020-04-01 12:59 UTC, samburovam commented on samburova_mi/task4/Source.cpp
> +	int** GetInfo(int step)
Этот метод получает на вход количество шагов, ищет количество записей с данным количеством шагов, и записывает информацию о каждой записи в двумерный массив, в котором первый индекс-это количество найденных записей.

2020-04-01 12:59 UTC, samburovam commented on samburova_mi/task4/Source.cpp
> +	int GetCounter(int step)
Этот метод просто считает количество записей с данным кол-вом шагов, но он здесь только для удобства вывода в основной программе (чтобы получить значение counter)

2020-04-01 18:39 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +	int** GetInfo(int step)
Где в постановке задачи такой метод?

2020-04-01 18:40 UTC, alvls commented on samburova_mi/task4/Source.cpp
> +	int GetCounter(int step)
Где в постановке задачи такой метод?

2020-04-01 19:09 UTC, alvls commented
В текущем виде могу оценить так:

__Ваш   текущий балл:__ |  
-- | --
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,5

Будете пытаться повысить?

2020-04-02 19:05 UTC, alvls commented
+0.5 балла.

2020-04-03 16:04 UTC, merged