┐('～`;)┌
alvls/mp1-2020-1 pull request #44
Opened 2020-03-28 16:42 UTC by AnasteishA-1610

2020-03-31 16:01 UTC, alvls requested changes

2020-03-31 16:01 UTC, alvls commented on plenkova_ad/task4/Source.cpp
> +		return avg / count;
Если count окажется равен нулю, программа упадет.

2020-03-31 16:01 UTC, alvls commented on plenkova_ad/task4/Source.cpp
> +		return avg / count;
Если count окажется равен нулю, программа упадет.

2020-03-31 16:02 UTC, alvls commented
Анастасия, все хорошо с вашей реализацией, кроме двух замечаний. Исправьте.

2020-03-31 20:21 UTC, AnasteishA-1610 commented
Можно так оставить? Я конечно могу попробовать написать обработку исключений, но у меня с этим плоховато(((

2020-03-31 20:36 UTC, alvls commented
> 
> 
> Можно так оставить? Я конечно могу попробовать написать обработку исключений, но у меня с этим плоховато(((

Можно. Только
```
cout << "Error";
```
уберите.

2020-04-01 10:14 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2020-04-02 10:02 UTC, merged