Task4
alvls/mp1-2020-1 pull request #45
Opened 2020-03-28 20:49 UTC by Troeg13

2020-03-31 20:00 UTC, alvls requested changes

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Song::WriteCon1()
Этот метод лишний в данном классе. Фактически, это оформление вывода песенника, а не отдельной песни. Нужно перенести его.

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Song::WriteCon2()
Переименовать.

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Song::SaveInFile1(std::fstream &file)
См. замечание выше.

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Song::SaveInFile2(std::fstream &file)
Переименовать.

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Songbook::ChangeDataSong(std::string _song, std::vector<std::string> _data)//изменить данные о песне
Лучше назвать ChangeSongData или ChangeDataOfSong

2020-03-31 20:00 UTC, alvls commented on troegubova_aa/task4/Songbook.h
> +	std::vector<std::string> song;
Сэкономили на объявлении полей, а в результате непонятно, какое поле за что отвечает и вместо имен к полям нужно обращаться по номерам.

2020-03-31 20:00 UTC, alvls commented
Александра, с одной стороны неплохая реализация. С другой, некоторый проектные решения неудачные (см. выше).

2020-04-01 16:26 UTC, alvls requested changes

2020-04-01 16:26 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +int Songbook::GetCountSong()//узнать кол-во песен в песеннике
Назовите методы единообразно: либо GetCountOfSong, ChangeDataOfSong, либо GetSongCount, ChangeSongData.

2020-04-01 16:26 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +Songbook Songbook::GetSong(std::string _name_song, std::string _singer)//найти песню по назв. и исполнителю
Почему GetSong возвращает не песню, а песенник?

2020-04-01 16:26 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +Songbook Songbook::GetDataOfSongs(std::string _name, int human)//выдать все песни поэта, композитора, певца
Неудобно пользоваться методом, где нужно помнить, под каким номером скрывается поэт, композитор, исполнитель.

2020-04-01 16:26 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Songbook::WriteConDataSong()
Этот метод д.б. в секции private

2020-04-01 16:26 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +void Songbook::SaveInFileData(std::fstream &file)
Этот метод д.б. в секции private

2020-04-02 15:01 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 1,8
Качество кода: | 1,9
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,7

2020-04-02 15:43 UTC, Troeg13 commented
Здравствуйте, поясните, пожалуйста, за что конкретно был снижен балл, чтоб
в будущем не допускать таких ошибок.

С уважением,
Троегубова А.

чт, 2 апр. 2020 г., 22:02 Alexander Sysoyev <notifications@github.com>:

> Работа принята
> *Ваш текущий балл:*
> Функциональность: 4,0
> Качество проектирования: 1,8
> Качество кода: 1,9
> Бонус: 0,0
> Штраф: 0,0
> *Итого:* 7,7
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alvls/mp1-2020-1/pull/45#issuecomment-607900289>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANETIJ3ZDIJZ7BAC35WAAPLRKSSHDANCNFSM4LVWUCUA>
> .
>

2020-04-02 16:15 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +	Song song;
Лишняя переменная

2020-04-02 16:18 UTC, alvls commented on troegubova_aa/task4/Songbook.cpp
> +Songbook Songbook::GetDataOfSongs(std::string _name, std::string human)//выдать все песни поэта, композитора, певца
С параметром типа string стало несколько удобнее, чем с int, но лучше было бы сделать три отдельных public метода вида GetSongsOfPoet, в которых вызвать один private (ваш текущий).

2020-04-03 19:11 UTC, alvls commented
Хорошо. Добавлю вам 0.1 балла.

2020-04-03 19:11 UTC, merged