Киношка  и  прочее
alvls/mp1-2020-1 pull request #47
Opened 2020-03-29 18:08 UTC by GolovRibolov

2020-04-01 11:04 UTC, alvls requested changes

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +	Information(string _Name = "��� ��������", int _Year = 1, int _Month = 1, int _Fees = 0, int _Day = 1, string _Producer = "�� ������", string _Screenwriter = "�� ������", string _Composer = "�� ����
Почему параметр _Fees перед _Day? Странно выглядит.

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +					i++;
Порядок д.б. сначала по названию, потом по году.

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +	void SortAdd()
Почему метод так называется? Это сортировка, добавление или добавление с сортировкой?

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +	void SortFees()
Аналогично вопросу выше.
В целом д.б. один метод для сортировки

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +	int SearchFilmName(int tmp, string _Name)
Фильм должен искаться по названию и году, поскольку названия могут совпадать.

2020-04-01 11:04 UTC, alvls commented on golovkin_n/task4/Source.cpp
> +		Films[_index].setFees(_Fees);
Фильм определяется не индексом, а названием и годом

2020-04-01 11:06 UTC, alvls commented
Никита, исправьте замечания выше. Кроме того, в методах вида "выдать..." в задании имеется в виду, что метод должен вернуть, а не вывести на экран.

2020-04-06 12:10 UTC, GolovRibolov commented
Не мог исправить раньше, не имел доступа к компухтеру

2020-04-06 21:05 UTC, alvls commented
Исправили не все и не так, как я просил.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,0
Качество   проектирования: | 1,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,0

2020-04-08 11:56 UTC, merged