Task 4
alvls/mp1-2020-1 pull request #50
Opened 2020-03-29 21:05 UTC by yanok5

2020-04-02 08:00 UTC, alvls requested changes

2020-04-02 08:00 UTC, alvls commented on nenasheva.ya/task4/Weather.cpp
> +	}
В данном случае лучше бросить исключение

2020-04-02 08:00 UTC, alvls commented on nenasheva.ya/task4/Weather.cpp
> +	}
Переделайте метод, чтобы данные приходили через параметры, а не вводились пользователем.

2020-04-02 08:02 UTC, alvls commented
Яна, мне нравится ваша реализация. Но есть пара замечаний, см. выше.

2020-04-03 19:31 UTC, alvls requested changes

2020-04-03 19:31 UTC, alvls commented on nenasheva.ya/task4/Weather.cpp
> +	}
Блок try вы используете идеологически неверно, в нем должен быть код, который может приводить к исключениям, а не тот, в котором они выбрасываются.
Здесь должно быть только throw, ни try, ни catch - не нужны. Проверять исключения и ловить их должен вызывающий код.

2020-04-03 20:49 UTC, yanok5 commented
Хотите сказать, что я просто должна оставить throw и при неправильном вводе
даты должно быть такое?

пт, 3 апр. 2020 г. в 22:31, Alexander Sysoyev <notifications@github.com>:

> *@alvls* requested changes on this pull request.
> ------------------------------
>
> In nenasheva.ya/task4/Weather.cpp
> <https://github.com/alvls/mp1-2020-1/pull/50#discussion_r403265217>:
>
> > +	try
> +	{
> +		if (d2 < d1)
> +		{
> +			throw "Дата раньше, чем начало наблюдений";
> +		}
> +	}
> +	catch(char *str)
> +	{
> +		cout << str << endl;
> +	}
> +	
> +	try
> +	{
> +		if (d2 > d1 + 365)
> +		{
> +			throw "Дата позже, чем окончание наблюдений";
> +		}
> +	}
> +	catch (char *str)
> +	{
> +		cout << str << endl;
> +	}
>
> Блок try вы используете идеологически неверно, в нем должен быть код,
> который может приводить к исключениям, а не тот, в котором они
> выбрасываются.
> Здесь должно быть только throw, ни try, ни catch - не нужны. Проверять
> исключения и ловить их должен вызывающий код.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alvls/mp1-2020-1/pull/50#pullrequestreview-387526287>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANETI5W6FTECFQDI5EB4DALRKY2QTANCNFSM4LWD64FA>
> .
>

2020-04-04 06:13 UTC, alvls commented
Да, в методах класса нужно просто бросать исключение. Ловить их будет внешний код.

2020-04-04 20:24 UTC, alvls commented
Конечно, на замечания вы отреагировали с задержкой более суток. По идее уже должен наступить штраф за сдачу, но, учитывая ситуацию, я засчитаю вам полный балл.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2020-04-04 20:24 UTC, merged