Task1
alvls/mp1-2020-1 pull request #7
Opened 2020-02-21 17:36 UTC by maxkost

2020-03-01 18:15 UTC, alvls commented
У вас в имени папки пробел. У меня git отказывается работать с такой папкой. Соответственно, я не могу проверить ваши работы. Исправьте.

2020-03-01 18:32 UTC, maxkost commented
Папок с пробелами не нашел.
Нашел и удалил папку .vscode

2020-03-01 18:54 UTC, alvls commented
А это что: "kostyukov_mi /kostyukov_mi.sln"? В имени папки у вас пробел в конце.

2020-03-01 19:11 UTC, alvls commented
Задание 1 - отлично!

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,8
Штраф: | 0,0
__Итого:__ | 6,8

2020-03-02 13:01 UTC, alvls requested changes

2020-03-02 13:01 UTC, alvls commented on kostyukov_mi /task2/Vector.h
> +            memcpy(data, _data, sizeof(Type) * size);
Использование memcpy вносит ограничение на тип Type, которым м.б. инстанцирован шаблон (только POD данные). Лучше использовать std::copy.

2020-03-02 13:01 UTC, alvls commented on kostyukov_mi /task2/Vector.h
> +            delete data;
Ошибка в удалении

2020-03-02 13:01 UTC, alvls commented on kostyukov_mi /task2/Vector.h
> +            return v;
Оператор= реализован неверно. Используйте то, что мы обсуждали на паре.

2020-03-02 13:01 UTC, alvls commented on kostyukov_mi /task2/Vector.h
> +            delete data;
Неверное удаление

2020-03-02 13:01 UTC, alvls commented on kostyukov_mi /task2/Vector.h
> +            Type len;
Ошибка. len не равен 0.

2020-03-02 13:02 UTC, alvls commented
Максим, внесите правки по замечаниям по заданию 2.

2020-03-02 21:15 UTC, alvls requested changes

2020-03-02 21:15 UTC, alvls commented on kostyukov_mi/task2/Vector.h
> +        Vector operator=(const Vector &v)
Лучше вернуть ссылку

2020-03-02 21:15 UTC, alvls commented on kostyukov_mi/task2/Vector.h
> +            return v;
Нужно возвращать ссылку на себя, а не на тот объект, что передали в параметрах.

2020-03-02 21:15 UTC, alvls commented on kostyukov_mi/task2/Vector.h
> +            memcpy(buff, data, sizeof(Type)*size);
заменить

2020-03-03 21:00 UTC, alvls commented
Еще замечания

2020-03-04 18:58 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 6,2

2020-03-04 18:58 UTC, merged