задание 1 сделано
alvls/mp1-2020-1 pull request #9
Opened 2020-02-21 20:33 UTC by dariabnn

2020-03-01 19:49 UTC, alvls commented
Дарья, класс по заданию 1 нужно переделать. Замечания:
1. В классе должны быть конструкторы.
2. В классе не должно быть метода ввода. Параметры поступают в класс через конструктор или методы.
3. В методах класса не должно быть вывода на консоль. Вместо этого они должны возвращать результат.
Исправьте.

2020-03-02 18:41 UTC, alvls requested changes

2020-03-02 18:41 UTC, alvls commented on zaytseva_da/task1/task1.cpp
> +    void kg_oz()
Дарья, вы код проверяли? Почему в методах void?

2020-03-03 07:35 UTC, alvls commented
Теперь с методами все хорошо. Не хватает только конструктора и оператора присваивания. В следующих работах учтите.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,0
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,5

2020-03-03 08:01 UTC, alvls requested changes

2020-03-03 08:01 UTC, alvls commented on zaytseva_da/task2/task2.cpp
> +		*(str + index - 1) = symbol;
Ошибка в индексе. Кроме того, у вас уже есть правильный вариант оператора[], который позволяет и прочитать символ строки и записать в него, поэтому данный метод лишний.

2020-03-03 08:01 UTC, alvls commented on zaytseva_da/task2/task2.cpp
> +	bool palindrome()
Почему со строчной буквы?

2020-03-03 08:01 UTC, alvls commented on zaytseva_da/task2/task2.cpp
> +	int Ndifsymbol()
Неудачное название. Лучше, например, NumberOfDiffSimbols

2020-03-03 21:02 UTC, alvls requested changes

2020-03-03 21:02 UTC, alvls commented on zaytseva_da/task2/task2.cpp
> +		str[index - 1] = symbol;
Я же написал, ошибка в индексе. Почему -1?

2020-03-03 21:15 UTC, dariabnn commented on zaytseva_da/task2/task2.cpp
> +		str[index - 1] = symbol;
Я понятия не имею почему, но я была на 100% уверена, что строка начинается с 0 символа, а не заканчивается им. Видимо, произошел сбой системы в моей голове, извините, сейчас переделаю.

2020-03-03 21:31 UTC, alvls commented
Работа принята	
__Ваш текущий балл:__ 	
Функциональность: 	3,0
Качество проектирования: 	1,5
Качество кода: 	1,5
Бонус: 	0,0
Штраф: 	0,0
__Итого:__ 	6,0

2020-03-03 21:36 UTC, merged